const USERS={1111:{name:'John',role:'admin'},2222:{name:'Reid',role:'admin'},3333:{name:'Tiffany',role:'admin'},4444:{name:'Worker 1',role:'worker'},5555:{name:'Worker 2',role:'worker'},6666:{name:'Worker 3',role:'worker'}};
const PARKS=['Fantasy Land','Lions Park','Rockland Park','LeHew Park','Chimney Field','Eastham Park','Gertrude E. Miller Park','15th Street Fields','Soccer Plex','Skate Park','Boat Ramp Only Area','Bing Crosby Stadium','Warren County Community Center','Other Warren County Area'];
const $=id=>document.getElementById(id);let user=null;
function reports(){return JSON.parse(localStorage.getItem('parkReports')||'[]')}
function saveReports(v){localStorage.setItem('parkReports',JSON.stringify(v))}
function start(){PARKS.forEach(p=>{let o=document.createElement('option');o.value=p;o.textContent=p;$('park').appendChild(o)});$('loginBtn').onclick=()=>login($('pinInput').value.trim());$('reportForm').onsubmit=submitReport;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>show(b.dataset.tab));$('searchReports').oninput=draw;$('statusFilter').onchange=draw;$('logoutBtn').onclick=()=>{localStorage.removeItem('parkPin');location.reload()};$('exportBtn').onclick=()=>{};$('clearDoneBtn').onclick=()=>{saveReports(reports().filter(r=>r.status!=='Completed'));draw()};let pin=localStorage.getItem('parkPin');if(pin&&USERS[pin])login(pin);draw()}
function login(pin){if(!USERS[pin]){$('loginError').textContent='Bad PIN';return}user=USERS[pin];localStorage.setItem('parkPin',pin);$('loginView').classList.add('hidden');$('homeView').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('userName').textContent=user.name;$('roleLabel').textContent=user.role==='admin'?'Admin':'Worker';$('adminTab').classList.toggle('hidden',user.role!=='admin');draw()}
function show(name){document.querySelectorAll('.panel').forEach(p=>p.classList.add('hidden'));$(name).classList.remove('hidden');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));draw()}
function submitReport(e){e.preventDefault();if(!user){alert('Enter PIN');return}let description=$('description').value.trim();if(!description){alert('Add description');return}let item={id:String(Date.now()),park:$('park').value,category:$('category').value,priority:$('priority').value,description:description,status:'New',createdBy:user.name,createdAt:new Date().toISOString()};saveReports([item,...reports()]);$('reportForm').reset();show('reports');alert('Report submitted')}
function draw(){let list=$('reportList');if(!list)return;let q=($('searchReports')?.value||'').toLowerCase();let st=$('statusFilter')?.value||'all';let data=reports().filter(r=>(st==='all'||r.status===st)&&JSON.stringify(r).toLowerCase().includes(q));list.innerHTML=data.length?'':'<section class="card"><h2>No reports yet</h2></section>';data.forEach(r=>{let el=document.createElement('article');el.className='report';el.innerHTML='<h3>'+safe(r.park)+'</h3><p class="muted">'+safe(r.category)+' · '+safe(r.createdBy)+'</p><p>'+safe(r.description)+'</p><span class="badge '+safe(r.priority)+'">'+safe(r.priority)+'</span><span class="badge '+safe(r.status)+'">'+safe(r.status)+'</span><div class="actions"></div>';let a=el.querySelector('.actions');if(user&&user.role==='admin'){a.appendChild(button('Assigned',()=>status(r.id,'Assigned')));a.appendChild(button('In Progress',()=>status(r.id,'In Progress')));a.appendChild(button('Complete',()=>status(r.id,'Completed')))}list.appendChild(el)});let all=reports();$('statNew').textContent=all.filter(r=>r.status==='New').length;$('statOpen').textContent=all.filter(r=>r.status!=='Completed').length;$('statDone').textContent=all.filter(r=>r.status==='Completed').length}
function button(t,f){let b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=t;b.onclick=f;return b}
function status(id,s){saveReports(reports().map(r=>r.id===id?{...r,status:s}:r));draw()}
function safe(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
start();