const BASE_USERS={1111:{name:'John',role:'admin',active:true},2222:{name:'Reid',role:'admin',active:true},3333:{name:'Tiffany',role:'admin',active:true},4444:{name:'Rob',role:'admin',active:true},5555:{name:'Chris',role:'admin',active:true},6101:{name:'Marcus',role:'worker',active:true},6102:{name:'Anthony',role:'worker',active:true},6103:{name:'Skip',role:'worker',active:true},6104:{name:'Johnny',role:'worker',active:true},6105:{name:'Jeff',role:'worker',active:true}};
const PARKS=['Fantasy Land','Rockland Park','LeHew Park','Chimney Field','Eastham Park','Gertrude E. Miller Park','15th Street Fields','Soccer Plex','Skate Park','Boat Ramp Only Area','Bing Crosby Stadium','Raymond E. Santmyers Youth Center','Burrell Brooks Jr. Community Park','Happy Creek Park','Claude A. Stokes Jr. Community Swimming Pool','Warren County Community Center','Other Warren County Area'];
const $=id=>document.getElementById(id);let currentUser=null,currentPin='',completingId=null,deferredPrompt=null;
const store={get reports(){return JSON.parse(localStorage.getItem('parkReports')||'[]')},set reports(v){localStorage.setItem('parkReports',JSON.stringify(v))},get users(){return JSON.parse(localStorage.getItem('parkUsers')||'{}')},set users(v){localStorage.setItem('parkUsers',JSON.stringify(v))},get logs(){return JSON.parse(localStorage.getItem('parkLogs')||'[]')},set logs(v){localStorage.setItem('parkLogs',JSON.stringify(v))}};
function allUsers(){return {...BASE_USERS,...store.users}}
function user(pin){return allUsers()[pin]}
function isAdmin(){return currentUser?.role==='admin'}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function log(text){store.logs=[{at:new Date().toLocaleString(),by:currentUser?currentUser.name:'System',text},...store.logs]}
function activePeople(){return Object.entries(allUsers()).filter(([p,u])=>u.active!==false).sort((a,b)=>a[1].name.localeCompare(b[1].name))}
function init(){PARKS.forEach(p=>$('park').appendChild(new Option(p,p)));bind();let pin=localStorage.getItem('parkPin');if(pin&&user(pin))login(pin);renderReports();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
function bind(){
 $('loginBtn').onclick=()=>login($('pinInput').value.trim());$('pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')login($('pinInput').value.trim())});$('logoutBtn').onclick=()=>{localStorage.removeItem('parkPin');location.reload()};
 $('showRegBtn').onclick=()=>{$('loginView').classList.add('hidden');$('regView').classList.remove('hidden')};$('backLoginBtn').onclick=()=>{$('regView').classList.add('hidden');$('loginView').classList.remove('hidden')};$('regBtn').onclick=()=>createAccount($('regName').value.trim(),$('regPin').value.trim(),'worker',$('regMsg'),false);
 document.querySelectorAll('.tab[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('reportForm').onsubmit=saveReport;$('photo').onchange=e=>preview(e.target.files[0],'photoPreview');$('afterPhoto').onchange=e=>preview(e.target.files[0],'afterPreview');$('searchReports').oninput=renderReports;$('statusFilter').onchange=renderReports;$('exportBtn').onclick=exportReports;$('completeForm').addEventListener('submit',completeRepair);$('adminCreateBtn').onclick=()=>createAccount($('adminName').value.trim(),$('adminPin').value.trim(),$('adminRole').value,$('adminMsg'),true);$('csvBtn').onclick=downloadCSV;
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').classList.add('hidden')}}}
function login(pin){let u=user(pin);if(!u){$('loginError').textContent='That PIN is not set up.';return}if(u.active===false){$('loginError').textContent='That account is inactive.';return}currentUser=u;currentPin=pin;localStorage.setItem('parkPin',pin);$('loginView').classList.add('hidden');$('regView').classList.add('hidden');$('homeView').classList.remove('hidden');$('userName').textContent=currentUser.name;$('roleLabel').textContent=currentUser.role==='admin'?'Admin access':'Worker access';$('adminTab').classList.toggle('hidden',!isAdmin());$('logTab').classList.toggle('hidden',!isAdmin());fillAssign();renderReports()}
function showTab(name){document.querySelectorAll('.tab[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.add('hidden'));$(name).classList.remove('hidden');fillAssign();renderReports()}
function fillAssign(){let opts='<option value="">Unassigned</option>'+activePeople().map(([p,u])=>`<option value="${p}">${esc(u.name)} - ${esc(u.role)}</option>`).join('');$('assignTo').innerHTML=opts}
function createAccount(name,pin,role,msg,fromAdmin){if(!name){msg.textContent='Add a name.';return}if(!/^\d{4,6}$/.test(pin)){msg.textContent='PIN must be 4 to 6 numbers.';return}if(user(pin)){msg.textContent='That PIN is already used.';return}let u=store.users;u[pin]={name,role,active:true};store.users=u;msg.textContent=role==='admin'?'Admin account created.':'Worker account created.';if(fromAdmin){log(`${currentUser.name} created ${role} account for ${name}`);$('adminName').value='';$('adminPin').value='';$('adminRole').value='worker';fillAssign();renderEmployees()}else{$('regName').value='';$('regPin').value=''}}
function fileToDataUrl(file){return new Promise(res=>{if(!file)return res('');let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)})}
function preview(file,id){if(!file)return;fileToDataUrl(file).then(src=>{let img=$(id);img.src=src;img.classList.remove('hidden')})}
async function saveReport(e){e.preventDefault();let photo=await fileToDataUrl($('photo').files[0]);let pin=$('assignTo').value,ass=pin?user(pin):null;let r={id:Date.now().toString(36),park:$('park').value,category:$('category').value,priority:$('priority').value,description:$('description').value.trim(),photo,status:pin?'Assigned':'New',createdBy:currentUser.name,createdByPin:currentPin,createdAt:new Date().toISOString(),assignedPin:pin,assignedTo:ass?ass.name:'',completedBy:'',completedAt:'',completeNote:'',afterPhoto:'',archived:false,ym:new Date().toISOString().slice(0,7)};store.reports=[r,...store.reports];log(`${currentUser.name} submitted ${r.priority} report for ${r.park}${ass?' assigned to '+ass.name:''}`);$('reportForm').reset();$('photoPreview').classList.add('hidden');$('saveMsg').textContent='Submitted.';showTab('reportsPanel')}
function canSee(r){return isAdmin()||r.assignedPin===currentPin||r.createdByPin===currentPin||!r.assignedPin}
function matchFilter(r){let f=$('statusFilter').value;if(f==='all')return true;if(f==='Archived')return r.archived||r.status==='Archived';if(r.archived||r.status==='Archived')return false;if(f==='open')return true;if(f==='mine')return r.assignedPin===currentPin;return r.status===f}
function renderReports(){let list=$('reportList');if(!list)return;let q=($('searchReports')?.value||'').toLowerCase();let rows=store.reports.filter(r=>canSee(r)&&matchFilter(r)&&[r.park,r.category,r.priority,r.description,r.createdBy,r.assignedTo,r.status].join(' ').toLowerCase().includes(q));list.innerHTML=rows.length?'':'<section class="card"><h2>No reports found</h2><p class="muted">New or assigned reports will show here.</p></section>';rows.forEach(r=>list.appendChild(card(r)));let all=store.reports;$('statNew').textContent=all.filter(r=>r.status==='New'&&!r.archived).length;$('statOpen').textContent=all.filter(r=>!['Completed','Archived'].includes(r.status)&&!r.archived).length;$('statDone').textContent=all.filter(r=>r.status==='Completed'&&!r.archived).length;renderEmployees();renderLog()}
function card(r){let el=document.createElement('article');el.className='report '+((r.archived||r.status==='Archived')?'archived':'');el.innerHTML=`<h3>${esc(r.park)}</h3><p class="muted">${esc(r.category)} · Submitted by ${esc(r.createdBy)} · ${new Date(r.createdAt).toLocaleString()}</p><p>${esc(r.description)}</p><span class="pill">${esc(r.priority)}</span><span class="pill">${esc(r.status)}</span><span class="pill">Assigned: ${esc(r.assignedTo||'Unassigned')}</span>${r.photo?`<img class="report-photo" src="${r.photo}" alt="Before photo">`:''}${r.afterPhoto?`<p class="muted"><b>Repair:</b> ${esc(r.completeNote||'Completed')}</p><img class="report-photo" src="${r.afterPhoto}" alt="After photo">`:''}<div class="actions"></div>`;let a=el.querySelector('.actions');if(isAdmin()){let sel=document.createElement('select');sel.innerHTML='<option value="">Unassigned</option>'+activePeople().map(([p,u])=>`<option value="${p}">${esc(u.name)} - ${esc(u.role)}</option>`).join('');sel.value=r.assignedPin||'';a.appendChild(sel);a.appendChild(btn('Assign',()=>assignReport(r.id,sel.value)));['Assigned','In Progress'].forEach(s=>a.appendChild(btn(s,()=>setStatus(r.id,s))));a.appendChild(btn('Complete',()=>openComplete(r),'blue'));a.appendChild(btn(r.archived||r.status==='Archived'?'Unarchive':'Archive',()=>toggleArchive(r.id),'danger'))}else if(r.assignedPin===currentPin&&r.status!=='Completed'){a.appendChild(btn('In Progress',()=>setStatus(r.id,'In Progress')));a.appendChild(btn('Complete',()=>openComplete(r),'blue'))}return el}
function btn(text,fn,cls='secondary'){let b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=fn;return b}
function assignReport(id,pin){let u=pin?user(pin):null;store.reports=store.reports.map(r=>r.id===id?{...r,assignedPin:pin,assignedTo:u?u.name:'',status:pin&&r.status==='New'?'Assigned':r.status}:r);log(`${currentUser.name} assigned report ${id} to ${u?u.name:'Unassigned'}`);renderReports()}
function setStatus(id,status){store.reports=store.reports.map(r=>r.id===id?{...r,status}:r);log(`${currentUser.name} changed report ${id} to ${status}`);renderReports()}
function toggleArchive(id){let r=store.reports.find(x=>x.id===id),next=!(r?.archived||r?.status==='Archived');store.reports=store.reports.map(x=>x.id===id?{...x,archived:next,status:next?'Archived':'Completed'}:x);log(`${currentUser.name} ${next?'archived':'unarchived'} report ${id}`);renderReports()}
function openComplete(r){completingId=r.id;$('completeTitle').textContent=`${r.park} · ${r.description}`;$('completeNote').value='';$('afterPhoto').value='';$('afterPreview').classList.add('hidden');$('completeDialog').showModal()}
async function completeRepair(e){e.preventDefault();if(!completingId)return;let afterPhoto=await fileToDataUrl($('afterPhoto').files[0]);store.reports=store.reports.map(r=>r.id===completingId?{...r,status:'Completed',completedBy:currentUser.name,completedAt:new Date().toISOString(),completeNote:$('completeNote').value.trim(),afterPhoto}:r);log(`${currentUser.name} completed report ${completingId}`);completingId=null;$('completeDialog').close();renderReports()}
function renderEmployees(){let box=$('empList');if(!box||!isAdmin())return;let saved=store.users,all=allUsers();box.innerHTML='';Object.keys(all).sort((a,b)=>all[a].name.localeCompare(all[b].name)).forEach(pin=>{let u=all[pin],el=document.createElement('div');el.className='emp';el.innerHTML=`<h3>${esc(u.name)}</h3><p>PIN ${pin} · ${esc(u.role)} · ${u.active===false?'Inactive':'Active'} · ${saved[pin]?'Saved':'Built in'}</p><div class="grid2"></div>`;let g=el.querySelector('.grid2');g.appendChild(btn(u.role==='admin'?'Make Worker':'Make Admin',()=>changeRole(pin),'blue'));g.appendChild(btn(u.active===false?'Reactivate':'Deactivate',()=>toggleUser(pin),u.active===false?'secondary':'danger'));box.appendChild(el)})}
function saveUser(pin,u){let saved=store.users;saved[pin]=u;store.users=saved}
function changeRole(pin){let u=user(pin),role=u.role==='admin'?'worker':'admin';saveUser(pin,{...u,role});log(`${currentUser.name} changed ${u.name} to ${role}`);fillAssign();renderEmployees()}
function toggleUser(pin){let u=user(pin),active=u.active===false;saveUser(pin,{...u,active});log(`${currentUser.name} ${active?'reactivated':'deactivated'} ${u.name}`);fillAssign();renderEmployees()}
function renderLog(){let box=$('logList');if(!box||!isAdmin())return;box.innerHTML=store.logs.length?'':'<p class="muted">No activity yet.</p>';store.logs.forEach(x=>{let el=document.createElement('div');el.className='log';el.innerHTML=`<p>${esc(x.text)}</p><p class="muted">${esc(x.by)} · ${esc(x.at)}</p>`;box.appendChild(el)})}
function exportReports(){let blob=new Blob([JSON.stringify(store.reports,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='park-reports.json';a.click();URL.revokeObjectURL(url)}
function downloadCSV(){let m=$('monthPick').value||new Date().toISOString().slice(0,7),rows=store.reports.filter(r=>(r.ym||r.createdAt||'').slice(0,7)===m),csv='Date,Park,Category,Priority,Status,Assigned To,Submitted By,Archived,Description\n'+rows.map(r=>[r.createdAt,r.park,r.category,r.priority,r.status,r.assignedTo,r.createdBy,r.archived?'Yes':'No',r.description].map(v=>'"'+String(v||'').replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='park-report-'+m+'.csv';a.click();log(`${currentUser.name} downloaded monthly CSV for ${m}`)}
init();