const USERS={1111:{name:'John',role:'admin'},2222:{name:'Reid',role:'admin'},3333:{name:'Tiffany',role:'admin'},4444:{name:'Worker 1',role:'worker'},5555:{name:'Worker 2',role:'worker'},6666:{name:'Worker 3',role:'worker'}};
const PARKS=['Fantasy Land','Lions Park','Rockland Park','LeHew Park','Chimney Field','Eastham Park','Gertrude E. Miller Park','15th Street Fields','Soccer Plex','Skate Park','Boat Ramp Only Area','Bing Crosby Stadium','Raymond E. Santmyers Youth Center','Burrell Brooks Jr. Community Park','Happy Creek Park','Claude A. Stokes Jr. Community Swimming Pool','Warren County Community Center','Other Warren County Area'];
const $=id=>document.getElementById(id);let currentUser=null,completingId=null,deferredPrompt=null;const store={get reports(){return JSON.parse(localStorage.getItem('parkReports')||'[]')},set reports(v){localStorage.setItem('parkReports',JSON.stringify(v))}};
function init(){PARKS.forEach(p=>{let o=document.createElement('option');o.textContent=p;$('park').appendChild(o)});bind();let pin=localStorage.getItem('parkPin');if(pin&&USERS[pin])login(pin);renderReports();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js')}
function bind(){$('loginBtn').onclick=()=>login($('pinInput').value.trim());$('pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')login($('pinInput').value.trim())});$('logoutBtn').onclick=()=>{localStorage.removeItem('parkPin');location.reload()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('reportForm').onsubmit=saveReport;$('photo').onchange=e=>preview(e.target.files[0],'photoPreview');$('afterPhoto').onchange=e=>preview(e.target.files[0],'afterPreview');$('searchReports').oninput=renderReports;$('statusFilter').onchange=renderReports;$('exportBtn').onclick=exportReports;$('clearDoneBtn').onclick=clearCompleted;$('completeForm').addEventListener('submit',completeRepair);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('installBtn').classList.add('hidden')}}}
function login(pin){if(!USERS[pin]){$('loginError').textContent='That PIN is not set up.';return}currentUser=USERS[pin];localStorage.setItem('parkPin',pin);$('loginView').classList.add('hidden');$('homeView').classList.remove('hidden');$('logoutBtn').classList.remove('hidden');$('userName').textContent=currentUser.name;$('roleLabel').textContent=currentUser.role==='admin'?'Admin access':'Report access';$('adminTab').classList.toggle('hidden',currentUser.role!=='admin');renderReports()}
function showTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.add('hidden'));$(name).classList.remove('hidden');renderReports()}
function fileToDataUrl(file){return new Promise(res=>{if(!file)return res('');let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)})}
function preview(file,id){if(!file)return;fileToDataUrl(file).then(src=>{let img=$(id);img.src=src;img.classList.remove('hidden')})}
async function saveReport(e){e.preventDefault();let photo=await fileToDataUrl($('photo').files[0]);let r={id:Date.now().toString(36),park:$('park').value,category:$('category').value,priority:$('priority').value,description:$('description').value.trim(),photo,status:'New',createdBy:currentUser.name,createdAt:new Date().toISOString(),assignedTo:'',completedBy:'',completedAt:'',completeNote:'',afterPhoto:''};store.reports=[r,...store.reports];$('reportForm').reset();$('photoPreview').classList.add('hidden');showTab('reports')}
function renderReports(){let q=($('searchReports')?.value||'').toLowerCase(),status=$('statusFilter')?.value||'all',reports=store.reports.filter(r=>(status==='all'||r.status===status)&&[r.park,r.category,r.priority,r.description,r.createdBy,r.status].join(' ').toLowerCase().includes(q));let list=$('reportList');if(!list)return;list.innerHTML=reports.length?'':'<section class="card"><h2>No reports yet</h2><p class="muted">New reports will show here.</p></section>';reports.forEach(r=>list.appendChild(card(r)));let all=store.reports;$('statNew').textContent=all.filter(r=>r.status==='New').length;$('statOpen').textContent=all.filter(r=>r.status!=='Completed').length;$('statDone').textContent=all.filter(r=>r.status==='Completed').length}
function card(r){let el=document.createElement('article');el.className='report';el.innerHTML=`<h3>${esc(r.park)}</h3><p class="muted">${esc(r.category)} · ${esc(r.createdBy)} · ${new Date(r.createdAt).toLocaleString()}</p><p>${esc(r.description)}</p><span class="badge ${r.priority}">${r.priority}</span><span class="badge ${r.status.replaceAll(' ','')}">${r.status}</span>${r.photo?`<img src="${r.photo}" alt="Before photo">`:''}${r.afterPhoto?`<p class="muted"><b>Repair:</b> ${esc(r.completeNote||'Completed')}</p><img src="${r.afterPhoto}" alt="After photo">`:''}<div class="actions"></div>`;let a=el.querySelector('.actions');if(currentUser?.role==='admin'){['Assigned','In Progress'].forEach(s=>a.appendChild(btn(s,()=>setStatus(r.id,s))));a.appendChild(btn('Complete',()=>openComplete(r)));a.appendChild(btn('Delete',()=>deleteReport(r.id),'danger'))}return el}
function btn(text,fn,cls='secondary'){let b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=fn;return b}
function setStatus(id,status){store.reports=store.reports.map(r=>r.id===id?{...r,status,assignedTo:currentUser.name}:r);renderReports()}
function openComplete(r){completingId=r.id;$('completeTitle').textContent=`${r.park} · ${r.description}`;$('completeNote').value='';$('afterPhoto').value='';$('afterPreview').classList.add('hidden');$('completeDialog').showModal()}
async function completeRepair(e){e.preventDefault();if(!completingId)return;let afterPhoto=await fileToDataUrl($('afterPhoto').files[0]);store.reports=store.reports.map(r=>r.id===completingId?{...r,status:'Completed',completedBy:currentUser.name,completedAt:new Date().toISOString(),completeNote:$('completeNote').value.trim(),afterPhoto}:r);completingId=null;renderReports()}
function deleteReport(id){if(confirm('Delete this report from this phone?')){store.reports=store.reports.filter(r=>r.id!==id);renderReports()}}
function clearCompleted(){if(confirm('Clear completed reports from this phone?')){store.reports=store.reports.filter(r=>r.status!=='Completed');renderReports()}}
function exportReports(){let blob=new Blob([JSON.stringify(store.reports,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='park-reports.json';a.click();URL.revokeObjectURL(url)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
init();